# This is the configuration file for catnap.
# Here you can configure the stat colors,
# stat names, stat icons and more!
#
# https://github.com/iinsertNameHere/catnap

##############################################
##          FetchInfo stats Config          ##
##############################################
[stats]
username  = {icon = ">", name = "User", color = "!DT!"}
hostname  = {icon = ">", name = "Host", color = "!DT!"}
kernel    = {icon = ">", name = "Kernel", color = "!DT!"}
distro    = {icon = ">", name = "Distro", color = "!DT!"}
desktop   = {icon = ">", name = "Desktop", color = "!DT!"}
packages  = {icon = ">", name = "Packages", color = "!DT!"}
shell     = {icon = ">", name = "Shell", color = "!DT!"}
# weather   = {icon = " ", name = "weather", color = "(BE)"}
# cpu       = {icon = " ", name = "cpu", color = "(RD)"}
# gpu       = {icon = "󱔐 ", name = "gpu", color = "(MA)"}
# memory    = {icon = " ", name = "memory", color = "(YW)"}
# disk_0    = {icon = " ", name = "disk", color = "(GN)"}

##############################################
##               Misc Config                ##
##############################################
[misc]
borderstyle = "line"
layout = "Inline" # [Inline, ArtOnTop, StatsOnTop]
stats_margin_top = 0
location = "" # Used for fetching weather; leave empty to use the location of your IP; check https://wttr.in/:help for supported location types

[misc.figletLogos] # Requires Figlet.
enable = false
color  = "(YW)"
font   = "slant"
margin = [0, 0, 0,]

[misc.imageMode] # Requires Viu.
enable = false
path   = "/path/to/some/image.png" # Please only use absolute paths.
scale  = 18
margin = [2, 2, 3,]
